server:
  port: 8501

spring:
  application:
    name: eureka-client-one
eureka:
  instance:
    preferIpAddress: true
    #ip-address: 103.36.173.37
  client:
    service-url:
      defaultZone: http://peer1:10001/eureka/,http://peer2:10002/eureka/